### ISSUE TITLE
有没有办法在输入过程中使用这个功能

### ISSUE THREAD

**Issue by naosense** [BlindingDark/rime-lua-select-character#5]
比如我想输入`rime是个好输入法`，完整输入后，显示的候选为`rime是个号输入法`，我通过tab先确定了`rime是个`这几个字，这个时候输入ren，即”好人“，按[，期望”好“留下，现在是直接把前面确定的”rime是个“这几个字也给清除了，只留下了”好“字。

**Comment by naosense** [comment]
@BlindingDark 感觉是不是和`commit_text`有关系，感觉就是删多了
https://github.com/BlindingDark/rime-lua-select-character/blob/7aaea18604aae0a5ca56306061c5a3b8ae2a4fa9/lua/select_character.lua#L40

**Comment by BlindingDark** [comment]
试试最新版

**Comment by naosense** [comment]
> 试试最新版

不太行，现在虽然前面的“rime是个”留下了，但是后面的“输入法”却直接没了

**Comment by BlindingDark** [comment]
是的，实现整句流任意位置选词比较困难，有待进一步研究 API，现在只能支持结尾选词
